- name: Find out if {{ruby_ruby_version}} is already installed
  stat: path=/opt/rubies/{{ruby_ruby_version}}
  register: ruby_ruby_version_folder

- name: Install {{ruby_ruby_version}} if necessary
  command: '{{ruby_ruby_install_command}} ruby {{ruby_ruby_version|replace("ruby-", "")}} -- --disable-install-doc'
  when: not ruby_ruby_version_folder.stat.exists

- name: Install bundler
  gem: >
    executable="{{ruby_chruby_exec_command}} {{ruby_ruby_version}} -- gem"
    name=bundler
    state=present
    user_install=no
